<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\dicommover.ico</ApplicationIcon>
    <Version>1.5.0</Version>
    <AssemblyVersion>1.5.0.0</AssemblyVersion>
    <FileVersion>1.5.0.0</FileVersion>
    <InformationalVersion>1.5</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DebugType Condition="'$(Configuration)' == 'Release'">None</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\dicommover-logo.png" />
    <Resource Include="Assets\dicommover.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.2.6" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DicomMover.Tests\**\*.cs" />
    <None Remove="DicomMover.Tests\**\*" />
    <Compile Remove="research\**\*.cs" />
    <None Remove="research\**\*" />
  </ItemGroup>

</Project>
